### PR TITLE
Improve stability in windows

### LINKED ISSUE #9: StringIndexOutOfBoundsException in windows
**Describe the bug**
When trying to open a new file, client throws a StringIndexOutOfBoundsException and after some moment language server receives `shutdown` notification.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.lsp4intellij.utils.FileUtils.sanitizeURI(FileUtils.java:135)
	at com.github.lsp4intellij.utils.FileUtils.editorToURIString(FileUtils.java:94)
	at com.github.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:257)
	at com.github.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$0(IntellijLanguageClient.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Desktop:**
 - OS: Windows

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
Fixes #9.

### CODE REVIEW

**Comment by nixel2007** [comment]
@NipunaRanasinghe :(

```
2019-02-28 14:02:20,105 [   9415]   INFO - ntellij.IntellijLanguageClient - Added server definition for bsl 
2019-02-28 14:02:20,106 [   9416]   INFO - ntellij.IntellijLanguageClient - Added server definition for os 
2019-02-28 14:02:20,106 [   9416]   INFO - ntellij.IntellijLanguageClient - Added definition for command : path java args : -jar D:\git\1c-syntax\bsl-language-server\build\libs\bsl-language-server-0.4.0-dev+45.dev.jar --diagnosticLanguage en 
2019-02-28 14:02:20,106 [   9416]   INFO - .openapi.application.Preloader - org.github._1c_syntax.intellij.bsl.BSLPreloadingActivity took 7 ms 
2019-02-28 14:02:20,478 [   9788]   INFO - penapi.project.DumbServiceImpl - Running dumb mode task: com.intellij.util.indexing.UnindexedFilesUpdater@30d6df52 
2019-02-28 14:02:20,513 [   9823]   INFO - ntellij.internal.IconsLoadTime - IMG load time: ide_startup=18,32ms, average=0,92ms, median=1,46ms; number of icons: 20 
2019-02-28 14:02:20,513 [   9823]   INFO - ntellij.internal.IconsLoadTime - SVG load time: ide_startup=196,97ms, average=5,47ms, median=7,40ms; number of icons: 36 
2019-02-28 14:02:20,584 [   9894]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 104ms; general responsiveness: ok; EDT responsiveness: ok 
2019-02-28 14:02:20,676 [   9986]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 90ms; general responsiveness: ok; EDT responsiveness: ok 
2019-02-28 14:02:21,035 [  10345]   INFO - ntellij.IntellijLanguageClient - Opened РаботаСКоннекторами.os 
2019-02-28 14:02:21,036 [  10346]   INFO - ntellij.IntellijLanguageClient - Instantiating wrapper for os : file:///D:/git/nixel2007/entity/ 
2019-02-28 14:02:21,045 [  10355]   INFO - ntellij.IntellijLanguageClient - Adding file РаботаСКоннекторами.os 
2019-02-28 14:02:21,047 [  10357]  ERROR - plication.impl.ApplicationImpl - null 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at com.github.lsp4intellij.client.languageserver.serverdefinition.CommandServerDefinition.createConnectionProvider(CommandServerDefinition.java:42)
	at com.github.lsp4intellij.client.languageserver.serverdefinition.LanguageServerDefinition.start(LanguageServerDefinition.java:59)
	at com.github.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.start(LanguageServerWrapper.java:412)
	at com.github.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:254)
	at com.github.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$0(IntellijLanguageClient.java:148)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-02-28 14:02:21,053 [  10363]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2018.3  Build #IC-183.4284.148 
2019-02-28 14:02:21,053 [  10363]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-02-28 14:02:21,053 [  10363]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-02-28 14:02:21,062 [  10372]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: Language 1C (BSL) version: 0.2.0 
2019-02-28 14:02:21,062 [  10372]  ERROR - plication.impl.ApplicationImpl - Last Action:  
```

**Comment by NipunaRanasinghe** [comment]
@nixel2007  I've added another minor fix, so should be fixed by now. Could you please try with the latest jitpack build of master branch?

**Comment by nixel2007** [comment]
No crashes of LSP, but i still have some errors in logs (2 different kinds).

```
2019-03-01 11:29:23,067 [  12551]  ERROR - emon.impl.LocalInspectionsPass - Tool #LSP registers INFORMATION level problem in batch mode on BSL File. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations 
java.lang.Throwable: Tool #LSP registers INFORMATION level problem in batch mode on BSL File. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInBatch(LocalInspectionsPass.java:141)
	at com.github.lsp4intellij.editor.EditorEventManager.lambda$null$1(EditorEventManager.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.github.lsp4intellij.editor.EditorEventManager.lambda$runInspection$2(EditorEventManager.java:196)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:435)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-03-01 11:29:23,070 [  12554]  ERROR - emon.impl.LocalInspectionsPass - IntelliJ IDEA 2018.3  Build #IC-183.4284.85 
2019-03-01 11:29:23,070 [  12554]  ERROR - emon.impl.LocalInspectionsPass - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-03-01 11:29:23,070 [  12554]  ERROR - emon.impl.LocalInspectionsPass - OS: Windows 10 
2019-03-01 11:29:23,075 [  12559]  ERROR - emon.impl.LocalInspectionsPass - Plugin to blame: Language 1C (BSL) version: 0.2.0 
2019-03-01 11:29:23,075 [  12559]  ERROR - emon.impl.LocalInspectionsPass - Last Action:
```

and several warns like this:
``` 
2019-03-01 11:29:23,189 [  12673]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 11
  character = 123
] line : 	КлючХранилища = ПолучитьКлючХранилища(ОбъектМодели.ТипСущности(), ТипЗнч(Коннектор), СвойстваКоннектора.СтрокаСоединения); column : 126 offset : 340

**Comment by NipunaRanasinghe** [comment]
So the features ( completion and diagnostics ) are working with these warnings or still don't work at all?

**Comment by nixel2007** [comment]
Completion was disabled some time ago, I can check it later.
 I can't see any diagnostics in idea window, only this "warn" Messages for each of them.

**Comment by nixel2007** [comment]
Can i enable any debug logs for lsp4intellij? Or Maybe some remote debug session via skype/zoom/teamviewer?

**Comment by NipunaRanasinghe** [comment]
@nixel2007 forgive me for the late reply as I was busy with some other tasks :( Actually the error that you've encountered occurs after I've refactored and improved the diagnostic highlighting process. Since the fix seems to be non-trivial, I've reverted it back to the intellij-lsp way until I figure out the fix :) Could you please try with the master?

**Comment by nixel2007** [comment]
@NipunaRanasinghe good news - i see "errors" and "warnings" in idea :)

image

bad news - no highlighting or diagnostic messages on "hints" and "informations". but there is "inspection" bubble.

image

**Comment by NipunaRanasinghe** [comment]
@nixel2007 Oh great news! I'll try fix hints and information as well (should be a trivial fix). Were you able to check completion and goto definition as well?

**Comment by nixel2007** [comment]
I have only dummy implementation of completion this time. I'll try to write dummy goto and check both of them. But only on the next week.

**Pull request merged**
