### PR TITLE
Add formatting and hover support 

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
$subject.

### CODE REVIEW

**Comment by NipunaRanasinghe** [comment]
@nixel2007 sorry for being late for adding formatting support :) You can give it a try now!

**Comment by nixel2007** [comment]
@NipunaRanasinghe some gradle configuration error prevents jitpack from build - https://jitpack.io/com/github/NipunaRanasinghe/lsp4intellij/6dee1ebe32/build.log ^(

**Comment by NipunaRanasinghe** [comment]
@nixel2007 Oh sorry I've missed it somehow :/ You can use the latest master branch SNAPSHOT build now.

**Comment by nixel2007** [comment]
Ok, I'll check it asap.

Any news about hint/info diagnostics?

**Comment by NipunaRanasinghe** [comment]
I tried but couldn't find the cause. May be I'll try to set up your BSL language server and give it a try!

**Comment by nixel2007** [comment]
Do you need help in setting things uo?

**Comment by NipunaRanasinghe** [comment]
@nixel2007 I think so. I wanted to set up your BSL plugin, but ended up with the following error when trying to import that gradle project :( Any clue?

```
Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

```

**Comment by nixel2007** [comment]
Which version of idea do you use? I have latest stable idea (2018.3.5 IC) with 2017 IC as dependency. Also project is configured to use gradle wrapper and JDK 1.8

**Comment by NipunaRanasinghe** [comment]
I was using IDEA IC 2017.3 :) Migrating to the latest IDEA version did the trick.

**Comment by NipunaRanasinghe** [comment]
@nixel2007  Can you please provide me a code sample that produces hint/info diagnostics?

**Comment by nixel2007** [comment]
Sure, Just open test files from bsl-language-server. https://github.com/1c-syntax/bsl-language-server/blob/develop/src/test/resources/diagnostics/LineLengthDiagnostic.bsl

LineLengthDiagnostic provides diagnostics on information level

**Comment by nixel2007** [comment]
https://github.com/1c-syntax/bsl-language-server/blob/develop/src/test/resources/diagnostics/YoLetterUsageDiagnostic.bsl for hints

**Comment by nixel2007** [comment]
@NipunaRanasinghe yay!

format

Two questions:
* Is it okay that plugin.xml has red highlighting on override key?
image

I've tried to remove this key, but then I recieve two format popups, so i suggest this key should presense.

* When I press Ctrl-Alt-L in Java code, formatting process starts without popup. Popup ehm... popups (😄) only on Ctrl-Alt-Shift-L. With your format action I see popup on Ctrl-Alt-L too. Did i misconfigure something?

https://github.com/1c-syntax/intellij-language-1c-bsl/commit/3b759fccd80a8f1d7303f77bec6f8528d355840e

**Comment by NipunaRanasinghe** [comment]
Great! :D 

Regarding the `overrides` thing,  I had already followed the same way you tried and ended up having two popups. So I believe that it should be necessary.

Regarding the second question, you have to do a little fix in the above commit,

from
```xml
 <action class="com.github.lsp4intellij.actions.LSPShowReformatDialogAction" id="ReformatCode" use-shortcut-of="ReformatCode" overrides="true" text="Reformat Code"/>
```

to
```xml
 <action class="com.github.lsp4intellij.actions.LSPReformatAction" id="ReformatCode" use-shortcut-of="ReformatCode" overrides="true" text="Reformat Code"/>
```

Also please update your dependency to the latest master build ('com.github.NipunaRanasinghe:lsp4intellij:master-0.1.1-g9fc4603-15'), since I couldn't declare the `LSPReformatAction` as public. :(

**Comment by NipunaRanasinghe** [comment]
Update: Seems theres something wrong with the jitpack ATM since it doesn't contain artifacts even if the build is marked as successful. Already created a github issue (https://github.com/jitpack/jitpack.io/issues/3791).

**Comment by NipunaRanasinghe** [comment]
@nixel2007 jitpack is working now!

**Comment by nixel2007** [comment]
@NipunaRanasinghe it's working :)

**Pull request merged**
